// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrLzQmSXo3gvIjWCzZY7C45zsVWbysdEQ',
    appId: '1:584720474176:web:f42df841379912c8f13fa5',
    messagingSenderId: '584720474176',
    projectId: 'pruebaexamen-953b4',
    authDomain: 'pruebaexamen-953b4.firebaseapp.com',
    storageBucket: 'pruebaexamen-953b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNBH70mebww0Zyi2hH3KwZ0ES73UCLDM',
    appId: '1:584720474176:android:84079f2c76886635f13fa5',
    messagingSenderId: '584720474176',
    projectId: 'pruebaexamen-953b4',
    storageBucket: 'pruebaexamen-953b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBXnW4epNNrgrHFCptfO9IeW30k6Fsz0',
    appId: '1:584720474176:ios:18e4478088c7595cf13fa5',
    messagingSenderId: '584720474176',
    projectId: 'pruebaexamen-953b4',
    storageBucket: 'pruebaexamen-953b4.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );
}
